#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: false
  identity:
    hostname: ubuntu-server
    password: $6$.EBtzSOZolqm4Gbs$27G8kdOZPps3WfrBhEbzQsOEES3PbjUDIKpbA/utynZoJ/NhlWeh3DL.XrDtmZ0t8NbLpRYBXSJJ8GcoPycvi/
    realname: ubuntu
    username: ubuntu
  keyboard:
    layout: es
    toggle: null
    variant: ''
  locale: es_ES.UTF-8
  network:
    ethernets:
      ens33:
        addresses:
        - 192.168.1.250/24
        nameservers:
          addresses:
          - 1.1.1.1
          search: []
        routes:
        - to: default
          via: 192.168.1.1
    version: 2
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: lvm
